[brakes]
BRAKE_LOCK = [ 1, 3.250 ]
BRAKES = [ 525, 650 ]
EBRAKE = 875

[chassis]
AERO_CG = 47.402
AERO_COEFFICIENT = 0.285000
DRAG_COEFFICIENT = 0.450
FRONT_WEIGHT_BIAS = 52.750
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 6, 6 ]
ROLL_CENTER = 8.5
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 85, 85 ]
SHOCK_STIFFNESS = [ 60, 60 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 7, 7 ]
SPRING_STIFFNESS = [ 600, 625 ]
SWAYBAR_STIFFNESS = [ 200, 200 ]
TRAVEL = [ 6, 6 ]

[tires]
DYNAMIC_GRIP = [ 1.950, 2.050 ]
GRIP_SCALE = [ 1, 1.020 ]
STATIC_GRIP = [ 2.150, 2.250 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.6, 0.750, 1 ]
YAW_SPEED = 0.470

[transmission]
GEAR_RATIO = [ 2.6, 0, 2.7, 1.7, 1.170, 0.9, 0.780, 0.682000 ]
DIFFERENTIAL = [ 0.8, 0.8, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.3

[engine]
TORQUE = [ 198, 300, 525, 648, 640, 576, 498, 444, 396 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
MAX_RPM = 7800
RED_LINE = 6800
IDLE = 800

[induction]
LOW_BOOST = 0.3
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.030
SPOOL = 0.1
SPOOL_TIME_UP = 1.5
PSI = 12
HIGH_BOOST = 0.3

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]