[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 450, 570 ]
EBRAKE = 900

[chassis]
AERO_CG = 46.5
AERO_COEFFICIENT = 0.270
DRAG_COEFFICIENT = 0.350
FRONT_WEIGHT_BIAS = 52.201
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 9.150
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 90, 90 ]
SHOCK_STIFFNESS = [ 70, 70 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 7, 7 ]
SPRING_STIFFNESS = [ 750, 700 ]
SWAYBAR_STIFFNESS = [ 350, 350 ]
TRAVEL = [ 6, 6 ]

[tires]
DYNAMIC_GRIP = [ 1.925000, 2 ]
GRIP_SCALE = [ 1, 1.050 ]
STATIC_GRIP = [ 2.1, 2.2 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.6, 1, 1.2 ]
YAW_SPEED = 0.5

[transmission]
GEAR_RATIO = [ 2.8, 0, 3.670, 2.050, 1.462000, 1.1330, 0.9190, 0.720 ]
DIFFERENTIAL = [ 0.750, 0.750, 0.750 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0.5
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.2

[engine]
TORQUE = [ 204, 282, 423, 502, 487, 441, 399, 368, 347 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 15
MAX_RPM = 8400
RED_LINE = 7400
IDLE = 800

[induction]
LOW_BOOST = 0.2
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.2
SPOOL_TIME_UP = 1.7
PSI = 12
HIGH_BOOST = 0.275000

[pvehicle]
TENSOR_SCALE = [ 1, 3.560, 1 ]