[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 475, 600 ]
EBRAKE = 925

[chassis]
AERO_CG = 47.750
AERO_COEFFICIENT = 0.3
DRAG_COEFFICIENT = 0.320
FRONT_WEIGHT_BIAS = 54
RENDER_MOTION = 1
RIDE_HEIGHT = [ 6, 6 ]
ROLL_CENTER = 9
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.2, 0.2 ]
SHOCK_EXT_STIFFNESS = [ 75, 77 ]
SHOCK_STIFFNESS = [ 60, 50 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 7.5, 7.5 ]
SPRING_STIFFNESS = [ 650, 600 ]
SWAYBAR_STIFFNESS = [ 200, 200 ]
TRAVEL = [ 8, 8 ]

[tires]
DYNAMIC_GRIP = [ 2, 2 ]
GRIP_SCALE = [ 1.175000, 1.225000 ]
STATIC_GRIP = [ 2.2, 2.3 ]
STEERING = 0.9
YAW_CONTROL = [ 0.3, 0.650, 1, 1.2 ]
YAW_SPEED = 0.250

[transmission]
GEAR_RATIO = [ 3.2, 0, 4.1, 2.530, 1.670, 1.230, 1, 0.830 ]
DIFFERENTIAL = [ 0.8, 0.8, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.4

[engine]
TORQUE = [ 170, 251, 340, 428, 467, 452, 411, 375, 350 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
MAX_RPM = 9500
RED_LINE = 8500
IDLE = 800

[induction]
LOW_BOOST = 0.2
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.2
SPOOL_TIME_UP = 2
PSI = 12
HIGH_BOOST = 0.2

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]