[brakes]
BRAKE_LOCK = [ 1, 2.5 ]
BRAKES = [ 280, 400 ]
EBRAKE = 550

[chassis]
AERO_CG = 47
AERO_COEFFICIENT = 0.077
DRAG_COEFFICIENT = 0.33
FRONT_WEIGHT_BIAS = 55
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8.850, 8.850 ]
ROLL_CENTER = 12.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.5, 0.5 ]
SHOCK_EXT_STIFFNESS = [ 50, 50 ]
SHOCK_STIFFNESS = [ 40, 40 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 6.250, 6 ]
SPRING_STIFFNESS = [ 392, 350 ]
SWAYBAR_STIFFNESS = [ 50, 45 ]
TRAVEL = [ 7.5, 7.5 ]

[tires]
DYNAMIC_GRIP = [ 1.58, 1.58 ]
GRIP_SCALE = [ 1.010, 1 ]
STATIC_GRIP = [ 1.76, 1.76 ]
STEERING = 1.050
YAW_CONTROL = [ 0.1, 0.250, 0.4, 0.5 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 2.6, 0, 3.380, 1.760, 1.180, 0.89, 0.7 ]
DIFFERENTIAL = [ 0.650, 0.650, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 1
CLUTCH_SLIP = 0.7
SHIFT_SPEED = 0.250
FINAL_GEAR = 4.050

[engine]
TORQUE = [ 85, 110, 151, 180, 180, 165, 150, 138, 130 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 8
MAX_RPM = 7000
RED_LINE = 6500
IDLE = 800

[induction]
LOW_BOOST = 0.1
SPOOL_TIME_DOWN = 0.250
VACUUM = 0
SPOOL = 0
SPOOL_TIME_UP = 2
PSI = 10
HIGH_BOOST = 0.1

[pvehicle]
TENSOR_SCALE = [ 1.15, 2.6, 1 ]