[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 340, 480 ]
EBRAKE = 425

[chassis]
AERO_CG = 49
AERO_COEFFICIENT = 0.180
DRAG_COEFFICIENT = 0.370
FRONT_WEIGHT_BIAS = 53.201
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8.850, 8.850 ]
ROLL_CENTER = 9.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.2, 0.2 ]
SHOCK_EXT_STIFFNESS = [ 60, 60 ]
SHOCK_STIFFNESS = [ 50, 50 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 7.2, 7 ]
SPRING_STIFFNESS = [ 475, 450 ]
SWAYBAR_STIFFNESS = [ 200, 210 ]
TRAVEL = [ 7.5, 7.5 ]

[tires]
DYNAMIC_GRIP = [ 1.5, 1.5 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.7, 1.720 ]
STEERING = 1.1
YAW_CONTROL = [ 0.1, 0.2, 0.650, 1 ]
YAW_SPEED = 0.3

[transmission]
GEAR_RATIO = [ 2.7, 0, 2.970, 2.070, 1.510, 1.150, 0.920, 0.740 ]
DIFFERENTIAL = [ 0.650, 0.650, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.420

[engine]
TORQUE = [ 100, 150, 210, 300, 400, 370, 335, 305, 280 ]
ENGINE_BRAKING = [ 0.7, 0.750, 0.8 ]
FLYWHEEL_MASS = 12
MAX_RPM = 7500
RED_LINE = 6500
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1.5, 2, 1.5 ]