[brakes]
BRAKE_LOCK = [ 1, 1.5 ]
BRAKES = [ 425, 475 ]
EBRAKE = 700

[chassis]
AERO_CG = 47
AERO_COEFFICIENT = 0.197
DRAG_COEFFICIENT = 0.36
FRONT_WEIGHT_BIAS = 53.5
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 8.850, 8.850 ]
ROLL_CENTER = 11
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.350, 0.350 ]
SHOCK_EXT_STIFFNESS = [ 85, 85 ]
SHOCK_STIFFNESS = [ 70, 70 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 7, 6 ]
SPRING_STIFFNESS = [ 600, 575 ]
SWAYBAR_STIFFNESS = [ 150, 135 ]
TRAVEL = [ 7.5, 7.5 ]

[tires]
DYNAMIC_GRIP = [ 1.8, 1.8 ]
GRIP_SCALE = [ 1.03, 1.03 ]
STATIC_GRIP = [ 2, 2 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.5, 0.8, 1 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 2.5, 0, 3.380, 1.760, 1.180, 0.9, 0.710, 0.590 ]
DIFFERENTIAL = [ 0.7, 0.7, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 1
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.6

[engine]
TORQUE = [ 172.5, 230, 260, 280, 300, 305, 300, 292, 264 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 8
MAX_RPM = 7000
RED_LINE = 6500
IDLE = 800

[induction]
LOW_BOOST = 0.3
SPOOL_TIME_DOWN = 0.5
VACUUM = 0
SPOOL = 0
SPOOL_TIME_UP = 1
PSI = 12
HIGH_BOOST = 0.3

[pvehicle]
TENSOR_SCALE = [ 1.15, 2.6, 1 ]