[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 475, 600 ]
EBRAKE = 900

[chassis]
AERO_CG = 47
AERO_COEFFICIENT = 0.270
DRAG_COEFFICIENT = 0.3
FRONT_WEIGHT_BIAS = 53.849998
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 8.750
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 80, 80 ]
SHOCK_STIFFNESS = [ 60, 60 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 7.750, 8 ]
SPRING_STIFFNESS = [ 700, 700 ]
SWAYBAR_STIFFNESS = [ 250, 250 ]
TRAVEL = [ 5.5, 5.5 ]

[tires]
DYNAMIC_GRIP = [ 1.8, 1.8 ]
GRIP_SCALE = [ 1.050, 1.1 ]
STATIC_GRIP = [ 2.1, 2.2 ]
STEERING = 1
YAW_CONTROL = [ 0.150, 0.750, 1, 1.250 ]
YAW_SPEED = 0.3

[transmission]
GEAR_RATIO = [ 2.5, 0, 2.970, 1.9, 1.430, 1.1, 0.9, 0.750 ]
DIFFERENTIAL = [ 0.6, 0.6, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 0.9, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.1

[engine]
TORQUE = [ 153, 225, 333, 518, 577, 523, 451, 397, 352 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 14
MAX_RPM = 8000
RED_LINE = 7000
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]