[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 300, 368.799988 ]
EBRAKE = 450

[chassis]
AERO_CG = 48.250
AERO_COEFFICIENT = 0.150
DRAG_COEFFICIENT = 0.350
FRONT_WEIGHT_BIAS = 52.875000
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 10.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.5, 0.5 ]
SHOCK_EXT_STIFFNESS = [ 43, 47 ]
SHOCK_STIFFNESS = [ 37, 37 ]
SHOCK_VALVING = [ 10, 10 ]
SPRING_PROGRESSION = [ 6, 6.2 ]
SPRING_STIFFNESS = [ 300, 320 ]
SWAYBAR_STIFFNESS = [ 190, 195 ]
TRAVEL = [ 8.5, 8.5 ]

[tires]
DYNAMIC_GRIP = [ 1.3, 1.3 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.5, 1.5 ]
STEERING = 1.1
YAW_CONTROL = [ 0, 0, 0, 0 ]
YAW_SPEED = 0.375000

[transmission]
GEAR_RATIO = [ 2.6, 0, 2.8, 1.9, 1.4, 1.1, 0.870 ]
DIFFERENTIAL = [ 0.650, 0.650, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.7
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.070

[engine]
TORQUE = [ 145, 220, 340, 383, 330, 285, 255, 235, 220 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 12
MAX_RPM = 7000
RED_LINE = 6000
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]