[brakes]
BRAKE_LOCK = [ 1, 1 ]
BRAKES = [ 1000, 1000 ]
EBRAKE = 1000

[chassis]
AERO_CG = 54
AERO_COEFFICIENT = 0.450
DRAG_COEFFICIENT = 0
FRONT_WEIGHT_BIAS = 54
RENDER_MOTION = 1
RIDE_HEIGHT = [ 9, 9 ]
ROLL_CENTER = 10
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.1, 0.3 ]
SHOCK_EXT_STIFFNESS = [ 100, 100 ]
SHOCK_STIFFNESS = [ 90, 90 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 7.680, 7.680 ]
SPRING_STIFFNESS = [ 720, 680 ]
SWAYBAR_STIFFNESS = [ 485.329987, 485.329987 ]
TRAVEL = [ 8, 8 ]

[tires]
DYNAMIC_GRIP = [ 1.8, 1.8 ]
GRIP_SCALE = [ 2, 2 ]
STATIC_GRIP = [ 2.2, 2.2 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.350, 0.4, 0.6 ]
YAW_SPEED = 0.650

[transmission]
GEAR_RATIO = [ 3.250, 0, 3.6, 2.5, 1.5, 1.070, 0.9, 0.750 ]
DIFFERENTIAL = [ 0.710, 0.710, 0.5 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_CONVERTER = 2
TORQUE_SPLIT = 0.5
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.250

[engine]
TORQUE = [ 380, 450, 580, 670, 763, 740, 700, 660, 600 ]
ENGINE_BRAKING = [ 0.5, 0.5, 0.5 ]
FLYWHEEL_MASS = 8.5
MAX_RPM = 10
RED_LINE = 9000
IDLE = 800

[induction]
LOW_BOOST = 1
SPOOL_TIME_DOWN = 0
VACUUM = 0
SPOOL = 0
SPOOL_TIME_UP = 0
PSI = 5
HIGH_BOOST = 1

[pvehicle]
TENSOR_SCALE = [ 2, 2, 2 ]