[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]

[brakes]
BRAKE_LOCK = [ 1, 3.6 ]
BRAKES = [ 545, 600 ]
EBRAKE = 700

[chassis]
AERO_CG = 50
AERO_COEFFICIENT = 0.190
DRAG_COEFFICIENT = 0.350
FRONT_WEIGHT_BIAS = 50
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 8.5, 8.5 ]
ROLL_CENTER = 11.450
SHOCK_BLOWOUT = 7
SHOCK_DIGRESSION = [ 0.4, 0.4 ]
SHOCK_EXT_STIFFNESS = [ 66, 72 ]
SHOCK_STIFFNESS = [ 57, 60 ]
SHOCK_VALVING = [ 17, 17 ]
SPRING_PROGRESSION = [ 6, 7 ]
SPRING_STIFFNESS = [ 556, 700 ]
SWAYBAR_STIFFNESS = [ 300, 300 ]
TRAVEL = [ 7.5, 7.5 ]

[engine]
ENGINE_BRAKING = [ 0.8, 0.850, 0.9 ]
FLYWHEEL_MASS = 10
IDLE = 800
MAX_RPM = 7000
RED_LINE = 6000
TORQUE = [ 228, 358, 611, 716, 663, 580, 507, 449, 403 ]

[induction]
HIGH_BOOST = 0.175000
LOW_BOOST = 0.2
PSI = 13
SPOOL = 0
SPOOL_TIME_DOWN = 1.5
SPOOL_TIME_UP = 1.5
VACUUM = 0

[tires]
DYNAMIC_GRIP = [ 1.550, 1.550 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.8, 1.8 ]
STEERING = 1
YAW_CONTROL = [ 0.0250, 0.050, 0.0750, 0.1 ]
YAW_SPEED = 0.3

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.450, 0 ]
FINAL_GEAR = 3.6
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.6, 0, 3.750, 1.990, 1.420, 1.1, 0.890, 0.730 ]
SHIFT_SPEED = 0.250
TORQUE_SPLIT = 0.0