[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]

[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 700, 750 ]
EBRAKE = 750

[chassis]
AERO_CG = 50
AERO_COEFFICIENT = 0.2
DRAG_COEFFICIENT = 0.5
FRONT_WEIGHT_BIAS = 53
RENDER_MOTION = 0.750
RIDE_HEIGHT = [ 7.1, 7.1 ]
ROLL_CENTER = 11
SHOCK_BLOWOUT = 7
SHOCK_DIGRESSION = [ 0.4, 0.4 ]
SHOCK_EXT_STIFFNESS = [ 70, 70 ]
SHOCK_STIFFNESS = [ 60, 60 ]
SHOCK_VALVING = [ 18, 18 ]
SPRING_PROGRESSION = [ 7, 8.5 ]
SPRING_STIFFNESS = [ 700, 770 ]
SWAYBAR_STIFFNESS = [ 275, 350 ]
TRAVEL = [ 6, 6 ]

[engine]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
IDLE = 800
MAX_RPM = 7400
RED_LINE = 6400
TORQUE = [ 172, 345, 621, 752, 724, 629, 541, 479, 427 ]

[induction]
HIGH_BOOST = 0.150
LOW_BOOST = 0.150
PSI = 11
SPOOL = 0
SPOOL_TIME_DOWN = 0.250
SPOOL_TIME_UP = 2
VACUUM = 0

[tires]
DYNAMIC_GRIP = [ 1.7, 1.7 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.9, 1.9 ]
STEERING = 0.950
YAW_CONTROL = [ 0, 0.2, 0.3, 0.350 ]
YAW_SPEED = 0.3

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.850, 0 ]
FINAL_GEAR = 4.070
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.6, 0, 3.625000, 1.9, 1.370, 1.050, 0.850, 0.7 ]
SHIFT_SPEED = 0.250
TORQUE_SPLIT = 0.0