[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]

[brakes]
BRAKE_LOCK = [ 1, 3.1 ]
BRAKES = [ 500, 600 ]
EBRAKE = 700

[chassis]
AERO_CG = 50
AERO_COEFFICIENT = 0.170
DRAG_COEFFICIENT = 0.450
FRONT_WEIGHT_BIAS = 51
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7.1, 7.1 ]
ROLL_CENTER = 12
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.5, 0.5 ]
SHOCK_EXT_STIFFNESS = [ 50, 55 ]
SHOCK_STIFFNESS = [ 40, 45 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 6, 7 ]
SPRING_STIFFNESS = [ 425, 450 ]
SWAYBAR_STIFFNESS = [ 200, 200 ]
TRAVEL = [ 7, 7 ]

[engine]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 11
IDLE = 800
MAX_RPM = 7400
RED_LINE = 6400
TORQUE = [ 150, 300, 540, 654, 630, 547, 471, 417, 372 ]

[induction]
HIGH_BOOST = 0.1
LOW_BOOST = 0.1
PSI = 11
SPOOL = 0
SPOOL_TIME_DOWN = 0.250
SPOOL_TIME_UP = 2.650
VACUUM = 0

[tires]
DYNAMIC_GRIP = [ 1.4, 1.4 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.6, 1.6 ]
STEERING = 0.950
YAW_CONTROL = [ 0.1, 0.2, 0.450, 0.550 ]
YAW_SPEED = 0.3

[transmission]
CLUTCH_SLIP = 0.750
DIFFERENTIAL = [ 0, 0.850, 0 ]
FINAL_GEAR = 4.525000
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.6, 0, 3.650, 1.9, 1.350, 1.050, 0.8250, 0.7 ]
SHIFT_SPEED = 0.250
TORQUE_SPLIT = 0.0