[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]

[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 550, 675 ]
EBRAKE = 850

[chassis]
AERO_CG = 50
AERO_COEFFICIENT = 0.250
DRAG_COEFFICIENT = 0.4
FRONT_WEIGHT_BIAS = 52
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 10
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.4050, 0.405000 ]
SHOCK_EXT_STIFFNESS = [ 62, 70 ]
SHOCK_STIFFNESS = [ 60, 70 ]
SHOCK_VALVING = [ 16, 16 ]
SPRING_PROGRESSION = [ 6, 7 ]
SPRING_STIFFNESS = [ 490, 575 ]
SWAYBAR_STIFFNESS = [ 200, 300 ]
TRAVEL = [ 6.750, 6.750 ]

[engine]
ENGINE_BRAKING = [ 0.750, 0.820, 0.9 ]
FLYWHEEL_MASS = 12
IDLE = 750
MAX_RPM = 7250
RED_LINE = 6250
TORQUE = [ 286, 377, 610, 891, 890, 789, 700, 620, 560 ]

[induction]
HIGH_BOOST = 0.220
LOW_BOOST = 0.220
PSI = 9
SPOOL = 0
SPOOL_TIME_DOWN = 0
SPOOL_TIME_UP = 0
VACUUM = 0

[tires]
DYNAMIC_GRIP = [ 1.5, 1.650 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.7, 1.850 ]
STEERING = 1.050
YAW_CONTROL = [ 0.1, 0.2, 0.3, 0.4 ]
YAW_SPEED = 0.3

[transmission]
CLUTCH_SLIP = 0.7
DIFFERENTIAL = [ 0, 0.750, 0 ]
FINAL_GEAR = 4.250
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.6, 0, 3.4, 1.780, 1.250, 0.970, 0.8, 0.670 ]
SHIFT_SPEED = 0.250
TORQUE_SPLIT = 0.0