[brakes]
BRAKE_LOCK = [ 1, 2 ]
BRAKES = [ 725, 725 ]
EBRAKE = 950

[chassis]
AERO_CG = 45
AERO_COEFFICIENT = 4.5
DRAG_COEFFICIENT = 0.31
FRONT_WEIGHT_BIAS = 47
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 9.2
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 100, 100 ]
SHOCK_STIFFNESS = [ 72, 76 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 2, 2 ]
SPRING_STIFFNESS = [ 760, 800 ]
SWAYBAR_STIFFNESS = [ 200, 180 ]
TRAVEL = [ 6.5, 6.5 ]

[engine]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
IDLE = 800
MAX_RPM = 7500
RED_LINE = 7000
TORQUE = [ 200, 332, 416, 463, 505, 515, 500, 475, 420 ]

[induction]
HIGH_BOOST = 0.6
LOW_BOOST = 0.6
PSI = 14
SPOOL = 0
SPOOL_TIME_DOWN = 0
SPOOL_TIME_UP = 0
VACUUM = 0

[pvehicle]
TENSOR_SCALE = [ 1.25, 2.5, 1 ]

[tires]
DYNAMIC_GRIP = [ 2.0, 2.2 ]
GRIP_SCALE = [ 2.0, 2.2 ]
STATIC_GRIP = [ 2.2, 2.4 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.5, 0.7, 1 ]
YAW_SPEED = 0.4

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.5, 0 ]
FINAL_GEAR = 3.55
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.5, 0, 2.7, 1.71, 1.28, 1, 0.8, 0.65 ]
SHIFT_SPEED = 0.15
TORQUE_SPLIT = 0