[brakes]
BRAKE_LOCK = [ 1, 3.250 ]
BRAKES = [ 359, 475 ]
EBRAKE = 550

[chassis]
AERO_CG = 48.5
AERO_COEFFICIENT = 0.185000
DRAG_COEFFICIENT = 0.270
FRONT_WEIGHT_BIAS = 51
RENDER_MOTION = 1
RIDE_HEIGHT = [ 9, 9 ]
ROLL_CENTER = 9.5
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.350, 0.350 ]
SHOCK_EXT_STIFFNESS = [ 55, 60 ]
SHOCK_STIFFNESS = [ 40, 40 ]
SHOCK_VALVING = [ 19, 19 ]
SPRING_PROGRESSION = [ 6, 6 ]
SPRING_STIFFNESS = [ 300, 300 ]
SWAYBAR_STIFFNESS = [ 175, 175 ]
TRAVEL = [ 7, 7 ]

[tires]
DYNAMIC_GRIP = [ 1.480, 1.6 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.750, 1.760 ]
STEERING = 1.070
YAW_CONTROL = [ 0, 0, 0, 0 ]
YAW_SPEED = 1

[transmission]
GEAR_RATIO = [ 3.280, 0, 2.970, 2.070, 1.430, 1.1, 0.840, 0.570 ]
DIFFERENTIAL = [ 0.8, 0.8, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_CONVERTER = 1.5
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.460

[engine]
TORQUE = [ 110.639999, 147.520004, 191.779999, 258.160004, 324, 295, 258, 236, 221 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 14
MAX_RPM = 7200
RED_LINE = 6200
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 2.2, 1 ]