[brakes]
BRAKE_LOCK = [ 1, 1 ]
BRAKES = [ 650, 550 ]
EBRAKE = 900

[chassis]
AERO_CG = 48
AERO_COEFFICIENT = 2.14
DRAG_COEFFICIENT = 0.3
FRONT_WEIGHT_BIAS = 47.5
RENDER_MOTION = 1
RIDE_HEIGHT = [ 6.5, 6.5 ]
ROLL_CENTER = 9.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 90, 90 ]
SHOCK_STIFFNESS = [ 67, 70 ]
SHOCK_VALVING = [ 19.7, 19.7 ]
SPRING_PROGRESSION = [ 1, 1 ]
SPRING_STIFFNESS = [ 680, 720 ]
SWAYBAR_STIFFNESS = [ 175, 150 ]
TRAVEL = [ 6, 6 ]

[engine]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
IDLE = 800
MAX_RPM = 8000
RED_LINE = 7500
TORQUE = [ 140, 220, 260, 280, 300, 310, 300, 280, 240 ]

[induction]
HIGH_BOOST = 1
LOW_BOOST = 1
PSI = 13
SPOOL = 0
SPOOL_TIME_DOWN = 0
SPOOL_TIME_UP = 0
VACUUM = 0

[pvehicle]
TENSOR_SCALE = [ 1.3, 2.42, 1 ]

[tires]
DYNAMIC_GRIP = [ 1.95, 2.2 ]
GRIP_SCALE = [ 1.95, 2.2 ]
STATIC_GRIP = [ 2.15, 2.4 ]
STEERING = 1
YAW_CONTROL = [ 0.2, 0.5, 0.75, 1 ]
YAW_SPEED = 0.4

[transmission]
CLUTCH_SLIP = 0.85
DIFFERENTIAL = [ 0, 0.65, 0 ]
FINAL_GEAR = 3.364
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 3, 0, 2.875, 1.773, 1.267, 1, 0.833, 0.711 ]
SHIFT_SPEED = 0.25
TORQUE_SPLIT = 0