[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 300, 425 ]
EBRAKE = 475

[chassis]
AERO_CG = 50
AERO_COEFFICIENT = 0.165000
DRAG_COEFFICIENT = 0.290
FRONT_WEIGHT_BIAS = 53.5
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 10
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.8, 0.8 ]
SHOCK_EXT_STIFFNESS = [ 60, 60 ]
SHOCK_STIFFNESS = [ 30, 30 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 5.5, 5 ]
SPRING_STIFFNESS = [ 400, 400 ]
SWAYBAR_STIFFNESS = [ 200, 250 ]
TRAVEL = [ 6.250, 6.5 ]

[tires]
DYNAMIC_GRIP = [ 1.4, 1.420 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.6, 1.650 ]
STEERING = 1.025000
YAW_CONTROL = [ 0.1, 0.2, 0.4, 0.5 ]
YAW_SPEED = 0.450

[transmission]
GEAR_RATIO = [ 2.5, 0, 3.570, 2.060, 1.380, 1, 0.760 ]
DIFFERENTIAL = [ 0.6, 0.6, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.1
FINAL_GEAR = 3.7

[engine]
TORQUE = [ 119, 151, 194, 235, 232, 216, 194, 178, 167 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 12
MAX_RPM = 7400
RED_LINE = 6400
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1.4, 2.5, 1.4 ]