[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 380, 500 ]
EBRAKE = 500

[chassis]
AERO_CG = 48
AERO_COEFFICIENT = 0.185000
DRAG_COEFFICIENT = 0.30
FRONT_WEIGHT_BIAS = 53
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7.5, 7.5 ]
ROLL_CENTER = 11
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.2, 0.2 ]
SHOCK_EXT_STIFFNESS = [ 70, 63 ]
SHOCK_STIFFNESS = [ 52, 47 ]
SHOCK_VALVING = [ 18, 18 ]
SPRING_PROGRESSION = [ 6.1, 6.5 ]
SPRING_STIFFNESS = [ 432, 375 ]
SWAYBAR_STIFFNESS = [ 90, 60 ]
TRAVEL = [ 7.5, 7.5 ]

[tires]
DYNAMIC_GRIP = [ 1.6, 1.6 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.8, 1.8 ]
STEERING = 1.075000
YAW_CONTROL = [ 0.1, 0.550, 0.7, 1 ]
YAW_SPEED = 0.41

[transmission]
GEAR_RATIO = [ 3.24, 0, 3.76, 2.270, 1.54, 1.187, 1, 0.843 ]
DIFFERENTIAL = [ 0.8, 0.8, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.25
FINAL_GEAR = 4.440

[engine]
TORQUE = [ 110, 130, 156, 186, 192, 180, 168, 156, 150 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
MAX_RPM = 9500
RED_LINE = 9000
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1.175, 3, 1 ]