[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 450, 600 ]
EBRAKE = 800

[chassis]
AERO_CG = 48.650002
AERO_COEFFICIENT = 0.230
DRAG_COEFFICIENT = 0.330
FRONT_WEIGHT_BIAS = 53
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 9
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 65, 65 ]
SHOCK_STIFFNESS = [ 60, 60 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 7, 7 ]
SPRING_STIFFNESS = [ 600, 650 ]
SWAYBAR_STIFFNESS = [ 150, 150 ]
TRAVEL = [ 7, 7 ]

[tires]
DYNAMIC_GRIP = [ 1.6, 1.6 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 2, 2 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.4, 0.8, 1 ]
YAW_SPEED = 0.7

[transmission]
GEAR_RATIO = [ 3.2880, 0, 3.483000, 2.015000, 1.391000, 1.1, 0.850, 0.7 ]
DIFFERENTIAL = [ 0.7, 0.7, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.1
FINAL_GEAR = 3.550

[engine]
TORQUE = [ 171, 239, 331, 445, 445, 388, 331, 296, 268 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 15
MAX_RPM = 9000
RED_LINE = 8000
IDLE = 800

[induction]
LOW_BOOST = 0.2
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.2
SPOOL_TIME_UP = 2
PSI = 15
HIGH_BOOST = 0.2

[pvehicle]
TENSOR_SCALE = [ 1, 3.5, 1 ]