[brakes]
BRAKE_LOCK = [ 1, 2 ]
BRAKES = [ 450, 400 ]
EBRAKE = 750

[chassis]
AERO_CG = 43
AERO_COEFFICIENT = 2.24
DRAG_COEFFICIENT = 0.28
FRONT_WEIGHT_BIAS = 46
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 11
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 65, 70 ]
SHOCK_STIFFNESS = [ 50, 55 ]
SHOCK_VALVING = [ 16.5, 16.5 ]
SPRING_PROGRESSION = [ 0, 0 ]
SPRING_STIFFNESS = [ 460, 540 ]
SWAYBAR_STIFFNESS = [ 150, 120 ]
TRAVEL = [ 6.5, 6.5 ]

[engine]
ENGINE_BRAKING = [ 0.8, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
IDLE = 1000
MAX_RPM = 8000
RED_LINE = 7500
TORQUE = [ 194, 324, 374, 400, 416, 427, 432, 420, 390 ]

[pvehicle]
TENSOR_SCALE = [ 1.175, 2.4, 1 ]

[tires]
DYNAMIC_GRIP = [ 1.8, 2.1 ]
GRIP_SCALE = [ 1.8, 2.1 ]
STATIC_GRIP = [ 2, 2.3 ]
STEERING = 1
YAW_CONTROL = [ 0.15, 0.3, 0.6, 0.9 ]
YAW_SPEED = 0.33

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.4, 0 ]
FINAL_GEAR = 3
GEAR_EFFICIENCY = [ 1, 1, 0.9, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 3.5, 0, 3.23, 2.19, 1.71, 1.39, 1.16, 0.93 ]
SHIFT_SPEED = 0.25
TORQUE_SPLIT = 0.0