[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 345, 500 ]
EBRAKE = 550

[chassis]
AERO_CG = 48
AERO_COEFFICIENT = 0.180
DRAG_COEFFICIENT = 0.290
FRONT_WEIGHT_BIAS = 53.5
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 10
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 50, 50 ]
SHOCK_STIFFNESS = [ 40, 40 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 6.5, 6.5 ]
SPRING_STIFFNESS = [ 425, 400 ]
SWAYBAR_STIFFNESS = [ 200, 200 ]
TRAVEL = [ 7, 7 ]

[tires]
DYNAMIC_GRIP = [ 1.550, 1.650 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.750, 1.850 ]
STEERING = 1.050
YAW_CONTROL = [ 0.1, 0.3, 0.6, 0.8 ]
YAW_SPEED = 0.5

[transmission]
GEAR_RATIO = [ 2.8, 0, 4.1, 2.860, 1.920, 1.450, 1.120, 0.960, 0.8 ]
DIFFERENTIAL = [ 0.820, 0.820, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.1

[engine]
TORQUE = [ 110, 170, 300, 340, 325, 275, 240, 220, 205 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 12
MAX_RPM = 7700
RED_LINE = 6700
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]