[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 475, 600 ]
EBRAKE = 800

[chassis]
AERO_CG = 48
AERO_COEFFICIENT = 0.240
DRAG_COEFFICIENT = 0.4
FRONT_WEIGHT_BIAS = 53
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 8.750
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.2, 0.2 ]
SHOCK_EXT_STIFFNESS = [ 85, 85 ]
SHOCK_STIFFNESS = [ 70, 70 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 8, 7.2 ]
SPRING_STIFFNESS = [ 750, 750 ]
SWAYBAR_STIFFNESS = [ 300, 300 ]
TRAVEL = [ 7.1, 7.1 ]

[tires]
DYNAMIC_GRIP = [ 1.9, 2 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 2.1, 2.2 ]
STEERING = 1
YAW_CONTROL = [ 0, 0.5, 0.750, 1 ]
YAW_SPEED = 0.5

[transmission]
GEAR_RATIO = [ 2.8, 0, 4.380, 2.860, 1.920, 1.450, 1.120, 0.960, 0.760 ]
DIFFERENTIAL = [ 0.7250, 0.6750, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 2.7

[engine]
TORQUE = [ 242, 374, 660, 748, 682, 572, 495, 435, 385 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 12
MAX_RPM = 7700
RED_LINE = 6700
IDLE = 800

[induction]
LOW_BOOST = 0.1
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.2
SPOOL_TIME_UP = 2
PSI = 12
HIGH_BOOST = 0.3

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]