[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 400, 475 ]
EBRAKE = 500

[chassis]
AERO_CG = 51.849998
AERO_COEFFICIENT = 0.150
DRAG_COEFFICIENT = 0.260
FRONT_WEIGHT_BIAS = 54.750
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 10.5
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.5, 0.5 ]
SHOCK_EXT_STIFFNESS = [ 42, 45 ]
SHOCK_STIFFNESS = [ 38.549999, 42.250 ]
SHOCK_VALVING = [ 17, 17 ]
SPRING_PROGRESSION = [ 5.5, 6.250 ]
SPRING_STIFFNESS = [ 375, 390 ]
SWAYBAR_STIFFNESS = [ 200, 270 ]
TRAVEL = [ 7, 7 ]

[tires]
DYNAMIC_GRIP = [ 1.350, 1.370 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.6, 1.620 ]
STEERING = 1
YAW_CONTROL = [ 0.0750, 0.1, 0.2, 0.150 ]
YAW_SPEED = 0.7

[transmission]
GEAR_RATIO = [ 2.5, 0, 2.930, 1.950, 1.410, 1.030, 0.770 ]
DIFFERENTIAL = [ 0.7, 0.7, 0.7 ]
GEAR_EFFICIENCY = [ 1, 1, 0.9, 0.9, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0.5
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.1
FINAL_GEAR = 3.6

[engine]
TORQUE = [ 110, 135, 185, 257, 248, 221, 197, 180, 165 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
MAX_RPM = 8000
RED_LINE = 7000
IDLE = 850

[induction]
LOW_BOOST = 0.1
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.2
SPOOL_TIME_UP = 2
PSI = 14
HIGH_BOOST = 0.2

[pvehicle]
TENSOR_SCALE = [ 1, 3, 1 ]