[brakes]
BRAKE_LOCK = [ 1, 1 ]
BRAKES = [ 550, 550 ]
EBRAKE = 800

[chassis]
AERO_CG = 45
AERO_COEFFICIENT = 2.7
DRAG_COEFFICIENT = 0.36
FRONT_WEIGHT_BIAS = 48
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 9.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 93, 93 ]
SHOCK_STIFFNESS = [ 70, 74 ]
SHOCK_VALVING = [ 18, 18 ]
SPRING_PROGRESSION = [ 1, 1 ]
SPRING_STIFFNESS = [ 720, 780 ]
SWAYBAR_STIFFNESS = [ 190, 160 ]
TRAVEL = [ 7, 7 ]

[engine]
ENGINE_BRAKING = [ 0.8, 0.85, 0.9 ]
FLYWHEEL_MASS = 12
IDLE = 800
MAX_RPM = 7500
RED_LINE = 7000
TORQUE = [ 222, 370, 442, 480, 502, 498, 482, 451, 381 ]

[pvehicle]
TENSOR_SCALE = [ 1.3, 2.44, 1 ]

[tires]
DYNAMIC_GRIP = [ 1.95, 2.2 ]
GRIP_SCALE = [ 1.95, 2.2 ]
STATIC_GRIP = [ 2.05, 2.4 ]
STEERING = 0.95
YAW_CONTROL = [ 0.3, 0.5, 0.7, 0.9 ]
YAW_SPEED = 0.4

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.5, 0 ]
FINAL_GEAR = 3.84
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.19, 0, 2.75, 1.773, 1.267, 1, 0.833, 0.71 ]
SHIFT_SPEED = 0.25
TORQUE_SPLIT = 0