[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 368.799988, 600 ]
EBRAKE = 700

[chassis]
AERO_CG = 46.5
AERO_COEFFICIENT = 0.185000
DRAG_COEFFICIENT = 0.350
FRONT_WEIGHT_BIAS = 52.5
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7.1, 7.1 ]
ROLL_CENTER = 10
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 50, 50 ]
SHOCK_STIFFNESS = [ 45, 45 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 6.5, 7 ]
SPRING_STIFFNESS = [ 400, 400 ]
SWAYBAR_STIFFNESS = [ 150, 200 ]
TRAVEL = [ 6, 6 ]

[tires]
DYNAMIC_GRIP = [ 1.750, 1.750 ]
GRIP_SCALE = [ 1.150, 1.150 ]
STATIC_GRIP = [ 1.9, 1.9 ]
STEERING = 1.050
YAW_CONTROL = [ 0.1, 0.3, 0.5, 0.6 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 2.6, 0, 2.660, 1.780, 1.3, 1, 0.740, 0.5 ]
DIFFERENTIAL = [ 0.850, 0.850, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.7
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.070

[engine]
TORQUE = [ 150, 275, 450, 523, 501, 443, 400, 380, 375 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 14
MAX_RPM = 7000
RED_LINE = 6000
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]