[pvehicle]
TENSOR_SCALE = [ 1.2, 3.150, 1, 0 ]

[brakes]
BRAKE_LOCK = [ 1, 3 ]
BRAKES = [ 450, 500 ]
EBRAKE = 675

[chassis]
AERO_CG = 49.8
AERO_COEFFICIENT = 0.190
DRAG_COEFFICIENT = 0.460
FRONT_WEIGHT_BIAS = 51.7300
RENDER_MOTION = 1
RIDE_HEIGHT = [ 9.3, 9 ]
ROLL_CENTER = 11.5
SHOCK_BLOWOUT = 7
SHOCK_DIGRESSION = [ 0.1, 0.4 ]
SHOCK_EXT_STIFFNESS = [ 52, 52 ]
SHOCK_STIFFNESS = [ 47, 47 ]
SHOCK_VALVING = [ 15, 15 ]
SPRING_PROGRESSION = [ 6, 5 ]
SPRING_STIFFNESS = [ 345, 475 ]
SWAYBAR_STIFFNESS = [ 45, 30 ]
TRAVEL = [ 9, 9 ]

[engine]
ENGINE_BRAKING = [ 0.750, 0.820, 0.9 ]
FLYWHEEL_MASS = 14
IDLE = 800
MAX_RPM = 6600
RED_LINE = 6100
TORQUE = [ 210, 350, 410, 450, 475, 490, 470, 425, 380 ]

[induction]
HIGH_BOOST = 0
LOW_BOOST = 0
PSI = 12
SPOOL = 0
SPOOL_TIME_DOWN = 0
SPOOL_TIME_UP = 0
VACUUM = 0

[tires]
DYNAMIC_GRIP = [ 1.6, 1.6 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.8, 1.8 ]
STEERING = 0.970
YAW_CONTROL = [ 0, 0, 0, 0 ]
YAW_SPEED = 0.405000

[transmission]
CLUTCH_SLIP = 0.8
DIFFERENTIAL = [ 0, 0.5, 0 ]
FINAL_GEAR = 3.540
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
GEAR_RATIO = [ 2.360, 0, 2.440, 1.770, 1.340, 1, 0.770, 0 ]
SHIFT_SPEED = 0.250
TORQUE_SPLIT = 0.0