[brakes]
BRAKE_LOCK = [ 1, 3.3 ]
BRAKES = [ 390, 500 ]
EBRAKE = 800

[chassis]
AERO_CG = 48.201
AERO_COEFFICIENT = 0.240
DRAG_COEFFICIENT = 0.390
FRONT_WEIGHT_BIAS = 54
RENDER_MOTION = 1
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 8.750
SHOCK_BLOWOUT = 8
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 60, 55 ]
SHOCK_STIFFNESS = [ 50, 45 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 8, 8 ]
SPRING_STIFFNESS = [ 650, 700 ]
SWAYBAR_STIFFNESS = [ 325, 320 ]
TRAVEL = [ 7, 7 ]

[tires]
DYNAMIC_GRIP = [ 1.9, 1.9 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 2.1, 2.1 ]
STEERING = 1.120
YAW_CONTROL = [ 0, 0.1, 0.2, 1 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 2.190, 0, 2.8, 1.870, 1.360, 1.070, 0.9, 0.750 ]
DIFFERENTIAL = [ 0.750, 0.750, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.820
SHIFT_SPEED = 0.250
FINAL_GEAR = 4.3

[engine]
TORQUE = [ 145, 175, 245, 350, 435, 395, 365, 342, 330 ]
ENGINE_BRAKING = [ 0.750, 0.820, 0.9 ]
FLYWHEEL_MASS = 11
MAX_RPM = 9400
RED_LINE = 8400
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1.1, 2, 1.1 ]