[brakes]
BRAKE_LOCK = [ 1, 2 ]
BRAKES = [ 700, 700 ]
EBRAKE = 900

[chassis]
AERO_CG = 46
AERO_COEFFICIENT = 5.2
DRAG_COEFFICIENT = 0.39
FRONT_WEIGHT_BIAS = 46
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 9.05
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 92, 96 ]
SHOCK_STIFFNESS = [ 69, 76 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 2, 2 ]
SPRING_STIFFNESS = [ 700, 800 ]
SWAYBAR_STIFFNESS = [ 240, 200 ]
TRAVEL = [ 6.5, 6.5 ]

[engine]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 9
IDLE = 900
MAX_RPM = 9000
RED_LINE = 8500
TORQUE = [ 240, 380, 450, 500, 550, 580, 560, 525, 465 ]

[pvehicle]
TENSOR_SCALE = [ 1.25, 2.4, 1 ]

[tires]
DYNAMIC_GRIP = [ 2.1, 2.3 ]
GRIP_SCALE = [ 2.1, 2.3 ]
STATIC_GRIP = [ 2.3, 2.5 ]
STEERING = 1
YAW_CONTROL = [ 0, 0.6, 0.9, 1 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 3, 0, 3.09, 1.98, 1.39, 1.11, 0.9, 0.75 ]
DIFFERENTIAL = [ 0, 0.6, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.15
FINAL_GEAR = 4