[brakes]
BRAKE_LOCK = [ 1, 2 ]
BRAKES = [ 600, 600 ]
EBRAKE = 800

[chassis]
AERO_CG = 45
AERO_COEFFICIENT = 2.8
DRAG_COEFFICIENT = 0.37
FRONT_WEIGHT_BIAS = 46
RENDER_MOTION = 1
RIDE_HEIGHT = [ 7, 7 ]
ROLL_CENTER = 9.25
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 84, 88 ]
SHOCK_STIFFNESS = [ 63, 70 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 1, 1 ]
SPRING_STIFFNESS = [ 630, 720 ]
SWAYBAR_STIFFNESS = [ 200, 170 ]
TRAVEL = [ 6.5, 6.5 ]

[engine]
ENGINE_BRAKING = [ 0.750, 0.820, 0.9 ]
FLYWHEEL_MASS = 9
IDLE = 800
MAX_RPM = 8900
RED_LINE = 8400
TORQUE = [ 192, 318, 378, 406, 422, 434, 432, 406, 360 ]

[pvehicle]
TENSOR_SCALE = [ 1.25, 2.4, 1 ]

[tires]
DYNAMIC_GRIP = [ 2, 2.2 ]
GRIP_SCALE = [ 2, 2.2 ]
STATIC_GRIP = [ 2.2, 2.4 ]
STEERING = 1
YAW_CONTROL = [ 0, 0.1, 0.2, 1 ]
YAW_SPEED = 0.4

[transmission]
GEAR_RATIO = [ 2.86, 0, 3.2, 1.87, 1.36, 1.07, 0.9, 0.75 ]
DIFFERENTIAL = [ 0, 0.6, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.25
FINAL_GEAR = 4.44