[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 360, 500 ]
EBRAKE = 550

[chassis]
AERO_CG = 49.701
AERO_COEFFICIENT = 0.170
DRAG_COEFFICIENT = 0.330
FRONT_WEIGHT_BIAS = 53
RENDER_MOTION = 1
RIDE_HEIGHT = [ 9, 9 ]
ROLL_CENTER = 10.5
SHOCK_BLOWOUT = 6
SHOCK_DIGRESSION = [ 0.350, 0.350 ]
SHOCK_EXT_STIFFNESS = [ 60, 55 ]
SHOCK_STIFFNESS = [ 45, 45 ]
SHOCK_VALVING = [ 24, 24 ]
SPRING_PROGRESSION = [ 5, 6 ]
SPRING_STIFFNESS = [ 450, 500 ]
SWAYBAR_STIFFNESS = [ 185, 185 ]
TRAVEL = [ 7, 6.5 ]

[tires]
DYNAMIC_GRIP = [ 1.6, 1.650 ]
GRIP_SCALE = [ 1, 1 ]
STATIC_GRIP = [ 1.850, 1.850 ]
STEERING = 1.025000
YAW_CONTROL = [ 0.050, 0.070, 0.150, 0.2 ]
YAW_SPEED = 0.650

[transmission]
GEAR_RATIO = [ 2.530, 0, 3.340, 2, 1.320, 1, 0.680 ]
DIFFERENTIAL = [ 0.8, 0.8, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 0
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.6

[engine]
TORQUE = [ 125, 165, 250, 320, 318, 275, 245, 230, 217 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 10
MAX_RPM = 7250
RED_LINE = 6250
IDLE = 800

[pvehicle]
TENSOR_SCALE = [ 1, 3.5, 1 ]