[brakes]
BRAKE_LOCK = [ 1, 3.5 ]
BRAKES = [ 390, 475 ]
EBRAKE = 750

[chassis]
AERO_CG = 47
AERO_COEFFICIENT = 0.240
DRAG_COEFFICIENT = 0.350
FRONT_WEIGHT_BIAS = 53.250
RENDER_MOTION = 0.5
RIDE_HEIGHT = [ 8, 8 ]
ROLL_CENTER = 9
SHOCK_BLOWOUT = 5
SHOCK_DIGRESSION = [ 0.1, 0.1 ]
SHOCK_EXT_STIFFNESS = [ 65, 65 ]
SHOCK_STIFFNESS = [ 60, 55 ]
SHOCK_VALVING = [ 20, 20 ]
SPRING_PROGRESSION = [ 7, 7 ]
SPRING_STIFFNESS = [ 500, 500 ]
SWAYBAR_STIFFNESS = [ 350, 275 ]
TRAVEL = [ 6.5, 6.5 ]

[tires]
DYNAMIC_GRIP = [ 1.850, 1.9 ]
GRIP_SCALE = [ 1.050, 1.1 ]
STATIC_GRIP = [ 2.1, 2.1 ]
STEERING = 1
YAW_CONTROL = [ 0.1, 0.6, 0.8, 1.250 ]
YAW_SPEED = 0.350

[transmission]
GEAR_RATIO = [ 2.7, 0, 3.5, 2.090, 1.470, 1.1, 0.870, 0.710 ]
DIFFERENTIAL = [ 0.7, 0.7, 0 ]
GEAR_EFFICIENCY = [ 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
TORQUE_SPLIT = 1
CLUTCH_SLIP = 0.8
SHIFT_SPEED = 0.250
FINAL_GEAR = 3.1

[engine]
TORQUE = [ 198, 385, 572, 653, 587, 517, 457, 407, 363 ]
ENGINE_BRAKING = [ 0.7, 0.8, 0.9 ]
FLYWHEEL_MASS = 15
MAX_RPM = 8000
RED_LINE = 7000
IDLE = 800

[induction]
LOW_BOOST = 0.2
SPOOL_TIME_DOWN = 0.250
VACUUM = -0.050
SPOOL = 0.250
SPOOL_TIME_UP = 2.5
PSI = 14
HIGH_BOOST = 0.1

[pvehicle]
TENSOR_SCALE = [ 1, 2, 1 ]